name: coveragemaster
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.16
  - scipy>=1.2
  - matplotlib>=3.0
  - sympy>=1.0
  - pywavelets>=1.0
  - pandas>=1.0
  - more-itertools>=8.0
  - pip
  - pip:
      - -e .    # installs coveragemaster package in editable mode from this directory
